import Link from 'next/link';
import { DocumentAnalysisResult } from '@/types/document';
import { ServiceRecommendationCard } from './ServiceRecommendationCard';
import { getService } from '@/data/services';

export function DocumentResult({ result }: { result: DocumentAnalysisResult }) {
  const recommendations = result.relevantServiceIds.map((id) => getService(id)).filter((service): service is NonNullable<ReturnType<typeof getService>> => service?.status === 'verified');
  return <section className="document-result" aria-live="polite"><div className="result-top"><div><p className="eyebrow">Document understanding</p><h2>{result.confidence === 'low' ? 'Possible document type' : 'Possible document'}</h2><strong>{result.documentType}</strong></div><span className={`confidence-badge ${result.confidence}`}>{result.confidence} confidence</span></div><div className="result-block"><p className="eyebrow">In simple language</p><p>{result.summary}</p></div><div className="result-block"><p className="eyebrow">What it appears to ask</p><p>{result.actionSummary || 'No clear action request was identified.'}</p></div>{(result.importantDates.length > 0 || result.reference !== 'Not identified') && <div className="result-details"><p className="eyebrow">Important details</p>{result.importantDates.map((date) => <div className="detail-row" key={date}><span>Date</span><strong>{date}</strong></div>)}{result.reference !== 'Not identified' && <div className="detail-row"><span>Reference</span><strong>{result.reference}</strong></div>}</div>}<div className="next-steps"><p className="eyebrow">What to do next</p><ol><li>Read the response instructions shown in the original document.</li><li>Verify the document and current process with the issuing authority.</li>{result.actionRequired && <li>Check any date stated in the document before deciding what to do.</li>}</ol></div>{recommendations.length > 0 ? <div className="result-recommendations"><p className="eyebrow">Relevant CivicGuide guide</p>{recommendations.map((service) => <ServiceRecommendationCard service={service} key={service.slug} />)}</div> : <div className="unverified-box"><strong>CivicGuide does not yet have a fully verified guide for this document type.</strong><span>Use the official source below for the authoritative process.</span></div>}{result.officialSources.length > 0 && <div className="result-sources"><p className="eyebrow">Where to verify it</p>{result.officialSources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.title} <span aria-hidden="true">↗</span><small>{source.organization}</small></a>)}</div>}<div className={`document-caution ${result.highRisk ? 'high-risk' : ''}`}><strong>{result.highRisk ? 'Important for legal or tax decisions' : 'A careful next step'}</strong><p>{result.caution}</p></div><p className="result-footer"><Link href="/ask-civicguide">Continue with CivicGuide Assistant <span aria-hidden="true">→</span></Link></p></section>;
  const assistantHref = `/ask-civicguide?documentType=${encodeURIComponent(result.documentType)}&confidence=${result.confidence}`;
  return <section className="document-result" aria-live="polite"><div className="result-top"><div><p className="eyebrow">Document understanding</p><h2>{result.confidence === 'low' ? 'Possible document type' : 'Possible document'}</h2><strong>{result.documentType}</strong></div><span className={`confidence-badge ${result.confidence}`}>{result.confidence} confidence</span></div><div className="result-block"><p className="eyebrow">In simple language</p><p>{result.summary}</p></div><div className="result-block"><p className="eyebrow">What it appears to ask</p><p>{result.actionSummary || 'No clear action request was identified.'}</p></div>{(result.importantDates.length > 0 || result.reference !== 'Not identified') && <div className="result-details"><p className="eyebrow">Important details</p>{result.importantDates.map((date) => <div className="detail-row" key={date}><span>Date</span><strong>{date}</strong></div>)}{result.reference !== 'Not identified' && <div className="detail-row"><span>Reference</span><strong>{result.reference}</strong></div>}</div>}<div className="next-steps"><p className="eyebrow">What to do next</p><ol><li>Read the response instructions shown in the original document.</li><li>Verify the document and current process with the issuing authority.</li>{result.actionRequired && <li>Check any date stated in the document before deciding what to do.</li>}</ol></div>{recommendations.length > 0 ? <div className="result-recommendations"><p className="eyebrow">Relevant CivicGuide guide</p>{recommendations.map((service) => <ServiceRecommendationCard service={service} key={service.slug} />)}</div> : <div className="unverified-box"><strong>CivicGuide does not yet have a fully verified guide for this document type.</strong><span>Use the official source below for the authoritative process.</span></div>}{result.officialSources.length > 0 && <div className="result-sources"><p className="eyebrow">Where to verify it</p>{result.officialSources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.title} <span aria-hidden="true">↗</span><small>{source.organization}</small></a>)}</div>}<div className={`document-caution ${result.highRisk ? 'high-risk' : ''}`}><strong>{result.highRisk ? 'Important for legal or tax decisions' : 'A careful next step'}</strong><p>{result.caution}</p></div><p className="result-footer"><Link href={assistantHref}>Continue with CivicGuide Assistant <span aria-hidden="true">→</span></Link></p></section>;
}
