import Link from 'next/link';
import { GovernmentService, ServiceDocument } from '@/types/service';

const unknown = 'Not yet verified';

function ExternalLink({ href, children }: { href: string; children: React.ReactNode }) {
  return <a className="official-link" href={href} target="_blank" rel="noreferrer">{children} <span aria-hidden="true">↗</span></a>;
}

function SummaryItem({ label, value }: { label: string; value?: string }) {
  return <div className="summary-item"><dt>{label}</dt><dd>{value || unknown}</dd></div>;
}

export function ServiceGuide({ service }: { service: GovernmentService }) {
  const documents: ServiceDocument[] | undefined = service.documentsStructured ?? service.documents?.map((name) => ({ name }));
  const sources = service.officialSources ?? [];
  const officialUrl = service.status === 'verified' ? service.onlineUrl : undefined;
  const steps = service.steps ?? [];
  return <>
    <nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>→</span><Link href="/services">Services</Link><span>→</span><span>{service.category}</span><span>→</span><strong>{service.name}</strong></nav>
    <header className="guide-hero"><div><span className="level-badge">{service.level === 'Central' ? 'Central Government' : 'Tamil Nadu Government'}</span><p className="eyebrow">{service.category}</p><h1>{service.name}</h1><p className="guide-lede">{service.shortDescription}</p></div><span className="sample-badge">{service.status === 'verified' ? 'Verified guide' : 'Sample guide'}</span></header>
    <div className="guide-layout"><main className="guide-content">
      <section className="summary-panel" aria-label="Service summary"><div className="summary-heading"><p className="eyebrow">At a glance</p><span>{service.status === 'verified' ? 'Verified against official sources' : 'Some details are still being verified'}</span></div><dl><SummaryItem label="Who is this for?" value={service.eligibility} /><SummaryItem label="How to apply" value={service.applicationMethod} /><SummaryItem label="Fee" value={service.fees} /><SummaryItem label="Processing time" value={service.processingTime} /><SummaryItem label="Department" value={service.department} /><SummaryItem label="Tracking" value={service.tracking} /></dl></section>
      <section className="guide-section decision-section" id="overview"><div className="section-kicker">01</div><div><h2>Is this the service you&apos;re looking for?</h2><p>{service.eligibility ? service.eligibility : 'This guide does not yet contain enough verified information to help you decide. Check the official information below before taking action.'}</p><Link className="text-action" href={`/ask-civicguide?serviceId=${service.slug}`}>Not sure? Ask CivicGuide <span aria-hidden="true">↗</span></Link></div></section>
      <section className="guide-section" id="documents"><div className="section-kicker">02</div><div><h2>What you&apos;ll need</h2>{documents?.length ? <div className="document-list">{documents.map((document) => <div className="document-item" key={document.name}><span className="document-check" aria-hidden="true">✓</span><div><h3>{document.name}</h3><span className="required-label">{document.required === false ? 'Optional' : document.required === true ? 'Required' : unknown}</span>{document.description && <p>{document.description}</p>}{document.alternatives?.length && <p><strong>Alternatives:</strong> {document.alternatives.join(', ')}</p>}{document.notes && <p><strong>Note:</strong> {document.notes}</p>}</div></div>)}</div> : <div className="unverified-box"><strong>Documents are not yet verified.</strong><span>We will add the exact requirements after checking the official source.</span></div>}</div></section>
      <section className="guide-section" id="apply"><div className="section-kicker">03</div><div><h2>How can you apply?</h2><div className="apply-methods"><div><span className="method-label">ONLINE</span><h3>{service.applicationMethod || unknown}</h3>{officialUrl ? <ExternalLink href={officialUrl}>Apply on official government website</ExternalLink> : <span className="muted-copy">Official online link not yet verified.</span>}</div><div><span className="method-label">OFFLINE</span><h3>{unknown}</h3><span className="muted-copy">Offline instructions will appear here when verified.</span></div></div></div></section>
      <section className="guide-section steps-section" id="steps"><div className="section-kicker">04</div><div><h2>Follow the steps</h2>{steps.length ? <div className="stepper">{steps.map((step, index) => <div className="step" key={`${step.title}-${index}`}><span className="step-number">{String(step.number ?? index + 1).padStart(2, '0')}</span><div><h3>{step.title}</h3><p>{step.description || unknown}</p>{step.action && <strong className="step-action">{step.action}</strong>}{step.officialUrl && service.status === 'verified' && <ExternalLink href={step.officialUrl}>View official instructions</ExternalLink>}{step.notes && <small>{step.notes}</small>}</div></div>)}</div> : <div className="unverified-box"><strong>Step-by-step instructions are not yet verified.</strong><span>We will show each action here once the official process has been checked.</span></div>}</div></section>
      <section className="guide-section cost-section" id="cost-time"><div className="section-kicker">05</div><div><h2>Cost &amp; time</h2><div className="cost-grid"><div><span>Fee</span><strong>{service.fees || unknown}</strong></div><div><span>Processing time</span><strong>{service.processingTime || unknown}</strong></div></div></div></section>
      <section className="guide-section" id="after-applying"><div className="section-kicker">06</div><div><h2>After you apply</h2>{service.afterApplying?.length ? <ol className="plain-list">{service.afterApplying.map((item) => <li key={item}>{item}</li>)}</ol> : <div className="unverified-box"><strong>What happens next is not yet verified.</strong><span>We will add the actual next stages instead of guessing.</span></div>}</div></section>
      <section className="guide-section" id="mistakes"><div className="section-kicker">07</div><div><h2>Common mistakes to avoid</h2>{service.commonMistakes?.length ? <ul className="plain-list">{service.commonMistakes.map((item) => <li key={item}>{item}</li>)}</ul> : <div className="unverified-box"><strong>Common mistakes will be added after verification.</strong></div>}</div></section>
      <section className="guide-section" id="troubleshooting"><div className="section-kicker">08</div><div><h2>Need help with a problem?</h2>{service.troubleshooting?.length ? <div className="trouble-list">{service.troubleshooting.map((item) => <div key={item.problem}><h3>{item.problem}</h3><p>{item.explanation || unknown}</p>{item.action && <strong>{item.action}</strong>}{item.officialUrl && service.status === 'verified' && <ExternalLink href={item.officialUrl}>Official help</ExternalLink>}</div>)}</div> : service.grievanceHelp ? <div className="unverified-box"><strong>Official help</strong><span>{service.grievanceHelp}</span></div> : <div className="unverified-box"><strong>Troubleshooting information is not yet verified.</strong><span>We will add supported problems and official help routes here.</span></div>}</div></section>
      <section className="official-section" id="official-information"><p className="eyebrow">Official information</p><h2>Use the official source for final confirmation.</h2><p>CivicGuide simplifies the information. For the authoritative process, always refer to the official government source.</p>{sources.length ? sources.map((source) => <div className="source-row" key={source.url}><div><strong>{source.title}</strong><span>{source.organization || source.department || service.department}</span>{source.type && <small>{source.type}</small>}</div><ExternalLink href={source.url}>Official government website</ExternalLink></div>) : <div className="source-row"><div><strong>Official source not yet added.</strong><span>{service.department}</span></div></div>}<small>Last verified: {service.lastVerified || unknown}</small></section>
      <div className="guide-disclaimer">CivicGuide India is an independent citizen-assistance platform and is not a government website. Information may change. Always confirm important details on the official government website.</div>
    </main><aside className="guide-sidebar"><div className="on-page"><strong>On this page</strong><a href="#overview">Overview</a><a href="#documents">What you&apos;ll need</a><a href="#apply">How to apply</a><a href="#steps">Steps</a><a href="#after-applying">After applying</a><a href="#official-information">Official information</a></div><div className="sidebar-help"><p className="eyebrow">Still not sure?</p><h3>Ask CivicGuide about this service.</h3><Link className="button button-dark" href={`/ask-civicguide?serviceId=${service.slug}`}>Ask a question <span aria-hidden="true">↗</span></Link></div>{officialUrl && <ExternalLink href={officialUrl}>Apply on official website</ExternalLink>}</aside></div>
  </>;
}